title: Fred Rinaldo
description: Business Analytics | SQL | Power BI | Data Analysis

remote_theme: "jekyll/minima"

minima:
  skin: auto

show_excerpts: false

github_username: fredr11

plugins:
  - jekyll-feed
