title: Fred Rinaldo
description: Business Analytics graduate and data professional with experience working in NDIS finance, reporting, and business intelligence. My background combines operational business knowledge with analytical skills, allowing me to translate complex data into practical insights that support decision-making.
theme: jekyll-theme-minimal
